title: Progressing as a Software Engineer
author: Adrian
email: mohabiradrian@gmail.com
description: This blog is to track my progress and understanding of new programming concepts and lagnuages I learn. > # this means to ignore newlines until "baseurl:"
 
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username: Adrian082818 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
